const weather = async (city) => {
  // def elementos DOM
  try {
    const cityName = document.querySelector('#cityName');
    const weatherStatusMain = document.querySelector('#weatherStatusMain');
    const temperaturaMain = document.querySelector('#temperaturaMain');
    const tempMaxMinMain = document.querySelector('#tempMaxMinMain');
    const temperaturaMainIcon = document.querySelector('#temperaturaMainIcon');
    const error = document.querySelector('#error');
    //
    const getWeather = await fetch(`http://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&lang=es&APPID=e6d7d470999d1a5432119e29077faf4d`, { mode: 'cors' });
    const getData = await getWeather.json();
    const cityLon = getData.coord.lon;
    const cityLat = getData.coord.lat;
    const getMoreWeather = await fetch(`https://api.openweathermap.org/data/2.5/onecall?lat=${cityLat}&lon=${cityLon}&units=metric&lang=es&appid=e6d7d470999d1a5432119e29077faf4d`, { mode: 'cors' });
    const getMoreData = await getMoreWeather.json();
    // si todo ok, se borra error
    error.style.visibility = 'hidden';
    // funcion para traducir main weather data
    const traducirMain = (data) => {
      if (data === 'Drizzle') {
        return 'Llovizna';
      } if (data === 'Clear') {
        return 'Despejado';
      } if (data === 'Rain') {
        return 'Lluvia';
      } if (data === 'Clouds') {
        return 'Nublado';
      } if (data === 'Mist') {
        return 'Niebla';
      } if (data === 'Thunderstorm') {
        return 'Tormenta';
      } if (data === 'Snow') {
        return 'Nieve';
      }
      // si no fue especificada, devuelve data en ingles
      return data;
    };
    // funcion para devolver link src con data icon
    const weatherImage = (weatherIconData) => `img/${weatherIconData}.png`;
    console.log('///////////////////');
    console.log('///////////////////');
    console.log('///////////////////');
    console.log('datos actuales');
    cityName.textContent = getData.name;
    console.log(getData);
    console.log(getData.weather[0].icon);
    weatherStatusMain.textContent = traducirMain(getData.weather[0].main);
    console.log(traducirMain(getData.weather[0].main));
    temperaturaMainIcon.src = weatherImage(getData.weather[0].icon);
    console.log(getData.weather[0].description);
    console.log('temperatura');
    temperaturaMain.textContent = `${Math.round(getData.main.temp)}°`;
    console.log('sensacion termica');
    console.log(`${Math.round(getData.main.feels_like)}°`);
    console.log('temp maxima');
    tempMaxMinMain.textContent = (`Max: ${Math.round(getData.main.temp_max)}° | Min: ${Math.round(getData.main.temp_min)}°`);
    console.log('temp minima');
    console.log(`${Math.round(getData.main.temp_min)}°`);
    console.log('humedad');
    console.log(`${getData.main.humidity}%`);
    console.log('presion');
    console.log(`${getData.main.pressure} hPa`);
    console.log('visibilidad');
    console.log(`${getData.visibility / 100} km`);
    console.log('amanecer');
    const { sunrise } = getData.sys;
    const sunriseData = new Date(sunrise * 1000);
    // string method para conseguir minutos en dos digitos;
    const sunriseTime = `${sunriseData.getHours()}:${String(sunriseData.getMinutes()).padStart(2, '0')}`;
    console.log(sunriseTime);
    console.log('atardecer');
    const { sunset } = getData.sys;
    const sunsetData = new Date(sunset * 1000);
    // string method para conseguir minutos en dos digitos;
    const sunsetTime = `${sunsetData.getHours()}:${String(sunsetData.getMinutes()).padStart(2, '0')}`;
    console.log(sunsetTime);
    console.log('viento');
    // funcion para pasar data viento a string
    function direccionViento(degree) {
      if (degree > 337.5) return 'Norte';
      if (degree > 292.5) return 'Noroeste';
      if (degree > 247.5) return 'Oeste';
      if (degree > 202.5) return 'Suroeste';
      if (degree > 157.5) return 'Sur';
      if (degree > 122.5) return 'Sureste';
      if (degree > 67.5) return 'Este';
      if (degree > 22.5) return 'Noreste';
      return 'Norte';
    }
    // math round method para tener velocidad sin decimal;
    console.log(`${direccionViento(getData.wind.deg)} ${Math.round(getData.wind.speed)} km/hr`);
    console.log('indice UV');
    console.log(getMoreData.current.uvi);
    console.log('precipitacion');
    // funcion para devolver 0 si no hay data de precipitacion
    const precipitacion = (data) => {
      let precipitacionData = data;
      if (precipitacionData === undefined) {
        precipitacionData = 0;
      }
      return precipitacionData;
    };
    console.log(getMoreData);
    console.log(`${precipitacion(getMoreData.daily[0].rain)} cm`);
    console.log('probabilidad de lluvia');
    console.log(`${Math.round(getMoreData.hourly[0].pop * 100)}%`);
    console.log('///////////////////');
    console.log('///////////////////');
    console.log('///////////////////');
    console.log('informe ampliado 12hrs');
    // def DOM ampliado 12hrs;
    const hour0Time = document.querySelector('#hour0Time');
    const hour0pop = document.querySelector('#hour0pop');
    const hour0Weather = document.querySelector('#hour0Weather');
    const hour0Temp = document.querySelector('#hour0Temp');
    hour0Time.textContent = `${new Date(getMoreData.hourly[0].dt * 1000).getHours()} hrs`;
    hour0pop.textContent = `${Math.round(getMoreData.hourly[0].pop * 100)}%`;
    hour0Weather.src = weatherImage(getMoreData.hourly[0].weather[0].icon);
    hour0Temp.textContent = `${Math.round(getMoreData.hourly[0].temp)}°`;
    const hour1Time = document.querySelector('#hour1Time');
    const hour1pop = document.querySelector('#hour1pop');
    const hour1Weather = document.querySelector('#hour1Weather');
    const hour1Temp = document.querySelector('#hour1Temp');
    hour1Time.textContent = `${new Date(getMoreData.hourly[1].dt * 1000).getHours()} hrs`;
    hour1pop.textContent = `${Math.round(getMoreData.hourly[1].pop * 100)}%`;
    hour1Weather.src = weatherImage(getMoreData.hourly[1].weather[0].icon);
    hour1Temp.textContent = `${Math.round(getMoreData.hourly[1].temp)}°`;
    const hour2Time = document.querySelector('#hour2Time');
    const hour2pop = document.querySelector('#hour2pop');
    const hour2Weather = document.querySelector('#hour2Weather');
    const hour2Temp = document.querySelector('#hour2Temp');
    hour2Time.textContent = `${new Date(getMoreData.hourly[2].dt * 1000).getHours()} hrs`;
    hour2pop.textContent = `${Math.round(getMoreData.hourly[2].pop * 100)}%`;
    hour2Weather.src = weatherImage(getMoreData.hourly[2].weather[0].icon);
    hour2Temp.textContent = `${Math.round(getMoreData.hourly[2].temp)}°`;
    const hour3Time = document.querySelector('#hour3Time');
    const hour3pop = document.querySelector('#hour3pop');
    const hour3Weather = document.querySelector('#hour3Weather');
    const hour3Temp = document.querySelector('#hour3Temp');
    hour3Time.textContent = `${new Date(getMoreData.hourly[3].dt * 1000).getHours()} hrs`;
    hour3pop.textContent = `${Math.round(getMoreData.hourly[3].pop * 100)}%`;
    hour3Weather.src = weatherImage(getMoreData.hourly[3].weather[0].icon);
    hour3Temp.textContent = `${Math.round(getMoreData.hourly[3].temp)}°`;
    const hour4Time = document.querySelector('#hour4Time');
    const hour4pop = document.querySelector('#hour4pop');
    const hour4Weather = document.querySelector('#hour4Weather');
    const hour4Temp = document.querySelector('#hour4Temp');
    hour4Time.textContent = `${new Date(getMoreData.hourly[4].dt * 1000).getHours()} hrs`;
    hour4pop.textContent = `${Math.round(getMoreData.hourly[4].pop * 100)}%`;
    hour4Weather.src = weatherImage(getMoreData.hourly[4].weather[0].icon);
    hour4Temp.textContent = `${Math.round(getMoreData.hourly[4].temp)}°`;
    const hour5Time = document.querySelector('#hour5Time');
    const hour5pop = document.querySelector('#hour5pop');
    const hour5Weather = document.querySelector('#hour5Weather');
    const hour5Temp = document.querySelector('#hour5Temp');
    hour5Time.textContent = `${new Date(getMoreData.hourly[5].dt * 1000).getHours()} hrs`;
    hour5pop.textContent = `${Math.round(getMoreData.hourly[5].pop * 100)}%`;
    hour5Weather.src = weatherImage(getMoreData.hourly[5].weather[0].icon);
    hour5Temp.textContent = `${Math.round(getMoreData.hourly[5].temp)}°`;
    const hour6Time = document.querySelector('#hour6Time');
    const hour6pop = document.querySelector('#hour6pop');
    const hour6Weather = document.querySelector('#hour6Weather');
    const hour6Temp = document.querySelector('#hour6Temp');
    hour6Time.textContent = `${new Date(getMoreData.hourly[6].dt * 1000).getHours()} hrs`;
    hour6pop.textContent = `${Math.round(getMoreData.hourly[6].pop * 100)}%`;
    hour6Weather.src = weatherImage(getMoreData.hourly[6].weather[0].icon);
    hour6Temp.textContent = `${Math.round(getMoreData.hourly[6].temp)}°`;
    const hour7Time = document.querySelector('#hour7Time');
    const hour7pop = document.querySelector('#hour7pop');
    const hour7Weather = document.querySelector('#hour7Weather');
    const hour7Temp = document.querySelector('#hour7Temp');
    hour7Time.textContent = `${new Date(getMoreData.hourly[7].dt * 1000).getHours()} hrs`;
    hour7pop.textContent = `${Math.round(getMoreData.hourly[7].pop * 100)}%`;
    hour7Weather.src = weatherImage(getMoreData.hourly[7].weather[0].icon);
    hour7Temp.textContent = `${Math.round(getMoreData.hourly[7].temp)}°`;
    const hour8Time = document.querySelector('#hour8Time');
    const hour8pop = document.querySelector('#hour8pop');
    const hour8Weather = document.querySelector('#hour8Weather');
    const hour8Temp = document.querySelector('#hour8Temp');
    hour8Time.textContent = `${new Date(getMoreData.hourly[8].dt * 1000).getHours()} hrs`;
    hour8pop.textContent = `${Math.round(getMoreData.hourly[8].pop * 100)}%`;
    hour8Weather.src = weatherImage(getMoreData.hourly[8].weather[0].icon);
    hour8Temp.textContent = `${Math.round(getMoreData.hourly[8].temp)}°`;
    const hour9Time = document.querySelector('#hour9Time');
    const hour9pop = document.querySelector('#hour9pop');
    const hour9Weather = document.querySelector('#hour9Weather');
    const hour9Temp = document.querySelector('#hour9Temp');
    hour9Time.textContent = `${new Date(getMoreData.hourly[9].dt * 1000).getHours()} hrs`;
    hour9pop.textContent = `${Math.round(getMoreData.hourly[9].pop * 100)}%`;
    hour9Weather.src = weatherImage(getMoreData.hourly[9].weather[0].icon);
    hour9Temp.textContent = `${Math.round(getMoreData.hourly[9].temp)}°`;
    const hour10Time = document.querySelector('#hour10Time');
    const hour10pop = document.querySelector('#hour10pop');
    const hour10Weather = document.querySelector('#hour10Weather');
    const hour10Temp = document.querySelector('#hour10Temp');
    hour10Time.textContent = `${new Date(getMoreData.hourly[10].dt * 1000).getHours()} hrs`;
    hour10pop.textContent = `${Math.round(getMoreData.hourly[10].pop * 100)}%`;
    hour10Weather.src = weatherImage(getMoreData.hourly[10].weather[0].icon);
    hour10Temp.textContent = `${Math.round(getMoreData.hourly[10].temp)}°`;
    const hour11Time = document.querySelector('#hour11Time');
    const hour11pop = document.querySelector('#hour11pop');
    const hour11Weather = document.querySelector('#hour11Weather');
    const hour11Temp = document.querySelector('#hour11Temp');
    hour11Time.textContent = `${new Date(getMoreData.hourly[11].dt * 1000).getHours()} hrs`;
    hour11pop.textContent = `${Math.round(getMoreData.hourly[11].pop * 100)}%`;
    hour11Weather.src = weatherImage(getMoreData.hourly[11].weather[0].icon);
    hour11Temp.textContent = `${Math.round(getMoreData.hourly[11].temp)}°`;
    const hour12Time = document.querySelector('#hour12Time');
    const hour12pop = document.querySelector('#hour12pop');
    const hour12Weather = document.querySelector('#hour12Weather');
    const hour12Temp = document.querySelector('#hour12Temp');
    hour12Time.textContent = `${new Date(getMoreData.hourly[12].dt * 1000).getHours()} hrs`;
    hour12pop.textContent = `${Math.round(getMoreData.hourly[12].pop * 100)}%`;
    hour12Weather.src = weatherImage(getMoreData.hourly[12].weather[0].icon);
    hour12Temp.textContent = `${Math.round(getMoreData.hourly[12].temp)}°`;
    console.log(`${new Date(getMoreData.hourly[0].dt * 1000).getHours()} hrs`);
    console.log(`${Math.round(getMoreData.hourly[0].temp)}°`);
    console.log(getMoreData.hourly[0].weather[0].main);
    console.log(`probabilidad de lluvia:${Math.round(getMoreData.hourly[0].pop * 100)}%`);
    console.log(`${new Date(getMoreData.hourly[1].dt * 1000).getHours()} hrs`);
    console.log(`${Math.round(getMoreData.hourly[1].temp)}°`);
    console.log(getMoreData.hourly[1].weather[0].main);
    console.log(`probabilidad de lluvia:${Math.round(getMoreData.hourly[1].pop * 100)}%`);
    console.log(`${new Date(getMoreData.hourly[2].dt * 1000).getHours()} hrs`);
    console.log(`${Math.round(getMoreData.hourly[2].temp)}°`);
    console.log(getMoreData.hourly[2].weather[0].main);
    console.log(`probabilidad de lluvia:${Math.round(getMoreData.hourly[2].pop * 100)}%`);
    console.log(`${new Date(getMoreData.hourly[3].dt * 1000).getHours()} hrs`);
    console.log(`${Math.round(getMoreData.hourly[3].temp)}°`);
    console.log(getMoreData.hourly[3].weather[0].main);
    console.log(`probabilidad de lluvia:${Math.round(getMoreData.hourly[3].pop * 100)}%`);
    console.log(`${new Date(getMoreData.hourly[4].dt * 1000).getHours()} hrs`);
    console.log(`${Math.round(getMoreData.hourly[4].temp)}°`);
    console.log(getMoreData.hourly[4].weather[0].main);
    console.log(`probabilidad de lluvia:${Math.round(getMoreData.hourly[4].pop * 100)}%`);
    console.log(`${new Date(getMoreData.hourly[5].dt * 1000).getHours()} hrs`);
    console.log(`${Math.round(getMoreData.hourly[5].temp)}°`);
    console.log(getMoreData.hourly[5].weather[0].main);
    console.log(`probabilidad de lluvia:${Math.round(getMoreData.hourly[5].pop * 100)}%`);
    console.log(`${new Date(getMoreData.hourly[6].dt * 1000).getHours()} hrs`);
    console.log(`${Math.round(getMoreData.hourly[6].temp)}°`);
    console.log(getMoreData.hourly[6].weather[0].main);
    console.log(`probabilidad de lluvia:${Math.round(getMoreData.hourly[6].pop * 100)}%`);
    console.log(`${new Date(getMoreData.hourly[7].dt * 1000).getHours()} hrs`);
    console.log(`${Math.round(getMoreData.hourly[7].temp)}°`);
    console.log(getMoreData.hourly[7].weather[0].main);
    console.log(`probabilidad de lluvia:${Math.round(getMoreData.hourly[7].pop * 100)}%`);
    console.log(`${new Date(getMoreData.hourly[8].dt * 1000).getHours()} hrs`);
    console.log(`${Math.round(getMoreData.hourly[8].temp)}°`);
    console.log(getMoreData.hourly[8].weather[0].main);
    console.log(`probabilidad de lluvia:${Math.round(getMoreData.hourly[8].pop * 100)}%`);
    console.log(`${new Date(getMoreData.hourly[9].dt * 1000).getHours()} hrs`);
    console.log(`${Math.round(getMoreData.hourly[9].temp)}°`);
    console.log(getMoreData.hourly[9].weather[0].main);
    console.log(`probabilidad de lluvia:${Math.round(getMoreData.hourly[9].pop * 100)}%`);
    console.log(`${new Date(getMoreData.hourly[10].dt * 1000).getHours()} hrs`);
    console.log(`${Math.round(getMoreData.hourly[10].temp)}°`);
    console.log(getMoreData.hourly[10].weather[0].main);
    console.log(`probabilidad de lluvia:${Math.round(getMoreData.hourly[10].pop * 100)}%`);
    console.log(`${new Date(getMoreData.hourly[11].dt * 1000).getHours()} hrs`);
    console.log(`${Math.round(getMoreData.hourly[11].temp)}°`);
    console.log(getMoreData.hourly[11].weather[0].main);
    console.log(`probabilidad de lluvia:${Math.round(getMoreData.hourly[11].pop * 100)}%`);
    console.log(`${new Date(getMoreData.hourly[12].dt * 1000).getHours()} hrs`);
    console.log(`${Math.round(getMoreData.hourly[12].temp)}°`);
    console.log(getMoreData.hourly[12].weather[0].main);
    console.log(`probabilidad de lluvia:${Math.round(getMoreData.hourly[12].pop * 100)}%`);
    console.log('///////////////////');
    console.log('///////////////////');
    console.log('///////////////////');
    console.log('informe semanal');
    console.log((new Date(getMoreData.daily[1].dt * 1000)).toLocaleString('default', { weekday: 'long' }));
    console.log(getMoreData.daily[1].weather[0].main);
    console.log(`probabilidad de lluvia: ${Math.round(getMoreData.daily[1].pop * 100)}%`);
    console.log(`Humedad: ${getMoreData.daily[1].humidity}%`);
    console.log(`Temperatura Max ${Math.round(getMoreData.daily[1].temp.max)}°`);
    console.log(`Temperatura Min ${Math.round(getMoreData.daily[1].temp.min)}°`);
    console.log((new Date(getMoreData.daily[2].dt * 1000)).toLocaleString('default', { weekday: 'long' }));
    console.log(getMoreData.daily[2].weather[0].main);
    console.log(`probabilidad de lluvia: ${Math.round(getMoreData.daily[2].pop * 100)}%`);
    console.log(`Humedad: ${getMoreData.daily[2].humidity}%`);
    console.log(`Temperatura Max ${Math.round(getMoreData.daily[2].temp.max)}°`);
    console.log(`Temperatura Min ${Math.round(getMoreData.daily[2].temp.min)}°`);
    console.log((new Date(getMoreData.daily[3].dt * 1000)).toLocaleString('default', { weekday: 'long' }));
    console.log(getMoreData.daily[3].weather[0].main);
    console.log(`probabilidad de lluvia: ${Math.round(getMoreData.daily[3].pop * 100)}%`);
    console.log(`Humedad: ${getMoreData.daily[3].humidity}%`);
    console.log(`Temperatura Max ${Math.round(getMoreData.daily[3].temp.max)}°`);
    console.log(`Temperatura Min ${Math.round(getMoreData.daily[3].temp.min)}°`);
    console.log((new Date(getMoreData.daily[4].dt * 1000)).toLocaleString('default', { weekday: 'long' }));
    console.log(getMoreData.daily[4].weather[0].main);
    console.log(`probabilidad de lluvia: ${Math.round(getMoreData.daily[4].pop * 100)}%`);
    console.log(`Humedad: ${getMoreData.daily[4].humidity}%`);
    console.log(`Temperatura Max ${Math.round(getMoreData.daily[4].temp.max)}°`);
    console.log(`Temperatura Min ${Math.round(getMoreData.daily[4].temp.min)}°`);
    console.log((new Date(getMoreData.daily[5].dt * 1000)).toLocaleString('default', { weekday: 'long' }));
    console.log(getMoreData.daily[5].weather[0].main);
    console.log(`probabilidad de lluvia: ${Math.round(getMoreData.daily[3].pop * 100)}%`);
    console.log(`Humedad: ${getMoreData.daily[5].humidity}%`);
    console.log(`Temperatura Max ${Math.round(getMoreData.daily[5].temp.max)}°`);
    console.log(`Temperatura Min ${Math.round(getMoreData.daily[5].temp.min)}°`);
    console.log((new Date(getMoreData.daily[6].dt * 1000)).toLocaleString('default', { weekday: 'long' }));
    console.log(getMoreData.daily[6].weather[0].main);
    console.log(`probabilidad de lluvia: ${Math.round(getMoreData.daily[6].pop * 100)}%`);
    console.log(`Humedad: ${getMoreData.daily[6].humidity}%`);
    console.log(`Temperatura Max ${Math.round(getMoreData.daily[6].temp.max)}°`);
    console.log(`Temperatura Min ${Math.round(getMoreData.daily[6].temp.min)}°`);
    console.log((new Date(getMoreData.daily[7].dt * 1000)).toLocaleString('default', { weekday: 'long' }));
    console.log(getMoreData.daily[7].weather[0].main);
    console.log(`probabilidad de lluvia: ${Math.round(getMoreData.daily[7].pop * 100)}%`);
    console.log(`Humedad: ${getMoreData.daily[7].humidity}%`);
    console.log(`Temperatura Max ${Math.round(getMoreData.daily[7].temp.max)}°`);
    console.log(`Temperatura Min ${Math.round(getMoreData.daily[7].temp.min)}°`);
  } catch {
    const error = document.querySelector('#error');
    error.style.visibility = 'visible';
  }
};
const buscar = document.querySelector('#buscar');
const city = document.querySelector('#city');
buscar.addEventListener('click', () => {
  const cityToSearch = city.value;
  const cityValue = cityToSearch.replace(' ', '+');
  weather(cityValue);
});
weather('buenos+aires');
